import type {Metadata} from "next";
import "./globals.css";
import React from "react";
import {AppRouterCacheProvider} from "@mui/material-nextjs/v15-appRouter";
import {Roboto} from "next/font/google";
import {ThemeProvider} from "@mui/system";
import {theme} from "@/themes";

const roboto = Roboto({
    weight: ['300', '400', '500', '700'],
    variable: '--font-roboto',
    display: 'swap',
    subsets: ['latin'],
})


export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body className={`${roboto.variable} antialiased`}>
        <AppRouterCacheProvider options={{key: 'css',}}>
            <ThemeProvider theme={theme}>
                {children}
            </ThemeProvider>
        </AppRouterCacheProvider>
        </body>
        </html>
    );
}
